apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-startup"
data:
  config.yml: |
    cameras:
      rtsp_cam:
        ffmpeg:
          output_args:
            record: preset-record-generic-audio-copy
          inputs:
            - path: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4 # <--- the name here must match the name of the camera in restream
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4 # <--- the name here must match the name of the camera_sub in restream
              input_args: preset-rtsp-restream
              roles:
                - detect