{{- if eq .Values.global.enableTraefikRoutes true }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix("/{{ .Values.config.UrlBase }}")
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-strip"     
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route-substack"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix("/auth","/lovelace","/energy","/map","/logbook","/media-browser","/history","/developer-tools","/config","/profile")
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
{{- end }}