image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: "stable"
  pullPolicy: Always
  containerPort: 5000
  hostname: frigate
  # env:
  #   - name: TZ
  #     value: UTC

config:
  UrlBase: nvr

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "frigate"