debug:
  # this will only set media to the local storage
  useLocalStore: false
  mediaCapacity: 100Gi

#################
# Global config #
#################
global:
  # This section is needed to use NFS for storage
  nfs:
    server: YOUR_NFS_SERVER
  # nfs config path
  configPath: YOUR_CONFIG_PATH
  # local storage path such as /mnt/d/kubestore
  hostPath: "YOUR_LOCAL_STORAGE" # use this path localized storage
  configCapacity: 10Gi # each service will be allocated the same capacity. Divide the total config capacity by the number of services that will be deployed
  # media NFS path
  mediaPath: YOUR_MEDIA_PATH
  mediaCapacity: 15Ti # total capacity of your NFS media share (unless you want a buffer)
  # linuxserver common variables
  timezone: Etc/UTC
  PGID: 0
  PUID: 0

##################
# Network config #
##################
enableTraefikRoutes: true

#######################################
# Service config - NFS optional mount #
#######################################
homeassist:
  # Use configPath for NFS... permission issues with nfs creation though
  # configPath: postgres
  # Use hostPath for local storage
  hostPath: homeassist
  fullnameOverride: homeassist

frigate:
  # Use configPath for NFS... permission issues with nfs creation though
  # configPath: postgres
  # Use hostPath for local storage
  hostPath: frigate
  fullnameOverride: frigate

mosquitto:
  # Use configPath for NFS... permission issues with nfs creation though
  # configPath: postgres
  # Use hostPath for local storage
  hostPath: mosquitto
  fullnameOverride: mosquitto