debug:
  # this will only set media to the local storage
  useLocalStore: false
  mediaCapacity: 100Gi

#################
# Global config #
#################
global:
  # this determines if routes will be creates for the child services
  enableTraefikRoutes: true
  # This section is needed to use NFS for storage
  nfs:
    server: YOUR_NFS_SERVER
  # nfs config path
  configPath: YOUR_CONFIG_PATH
  # local storage path such as /mnt/d/kubestore
  hostPath: "YOUR_LOCAL_STORAGE" # use this path localized storage
  configCapacity: 10Gi # each service will be allocated the same capacity. Divide the total config capacity by the number of services that will be deployed
  # media NFS path
  mediaPath: YOUR_MEDIA_PATH
  mediaCapacity: 15Ti # total capacity of your NFS media share (unless you want a buffer)
  # linuxs common variables
  timezone: Etc/UTC
  PGID: 0
  PUID: 0

#######################################
# Service config - NFS optional mount #
#######################################
frigate:
  # Use hostPath for local storage
  # hostPath: frigate
  # Use configPath for NFS... permission issues with nfs creation though
  configPath: frigate
  fullnameOverride: frigate

homeassist:
  # Use hostPath for local storage
  # hostPath: homeassist
  # Use configPath for NFS... permission issues with nfs creation though
  configPath: homeassist
  fullnameOverride: homeassist

mosquitto:
  # Use hostPath for local storage
  # hostPath: mosquitto
  # Use configPath for NFS... permission issues with nfs creation though
  configPath: mosquitto
  fullnameOverride: mosquitto
