#################
# Global config #
#################
global:
  # This section is needed to use NFS for storage
  nfs:
    server: 192.168.1.163
  # nfs config path
  configPath: YOUR_CONFIG_PATH
  # local storage path such as /mnt/d/kubestore
  hostPath: "YOUR_LOCAL_STORAGE" # use this path localized storage
  configCapacity: 10Gi # each service will be allocated the same capacity. Divide the total config capacity by the number of services that will be deployed
  # linux common variables
  timezone: Etc/UTC
  PGID: 0
  PUID: 0

##################
# Network config #
##################
enableTraefikRoutes: true
enablek8sDashboard: true
